### PR TITLE
use Pkg server and eager registry by default

### LINKED ISSUE #14: Reconsider using Pkg server by default for the registry
In 1.7, Pkg has moved to use a compressed registry by default. This avoids unpacking ~22 000 files and has some good performance improvements for the first time installing a registry (which is what CI does all the time):

**git** :

```jl
julia> @time Pkg.add("Example")
  Installing known registries into `~/.julia`
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
       Added registry `General` to `~/.julia/registries/General`
   Resolving package versions...
    Updating `/tmp/jl_nJuAcb/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `/tmp/jl_nJuAcb/Manifest.toml`
  [7876af07] + Example v0.5.3
 15.838710 seconds (8.68 M allocations: 301.542 MiB, 0.29% gc time, 1.04% compilation time)
```

**pkg server**:

```
julia> @time Pkg.add("Example")
  Installing known registries into `~/.julia`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `/tmp/jl_16gHZs/Project.toml`
  [7876af07] + Example v0.5.3
    Updating `/tmp/jl_16gHZs/Manifest.toml`
  [7876af07] + Example v0.5.3
  2.753616 seconds (5.57 M allocations: 355.760 MiB, 1.80% gc time, 0.09% compilation time)
```

This is on my Linux machine with a fast hard drive. On windows, the difference is much larger.

By the time https://github.com/julia-actions/julia-buildpkg/pull/6 was merged, the Pkg server would only serve the updated General once all the packages and artifacts were available. This is no longer the case and the Pkg server serves the updated registry straight away.

### PR DESCRIPTION
**Pull request by visr**
This speeds up julia-buildpkg considerably.
Fixes #14

### CODE REVIEW

**Comment by visr** [comment]
If this is merged, in the repo settings the required status check in the branch protection rules probably need to be updated. They are also outdated right now which is why the status for them doesn't get reported.

**Comment by SaschaMann** [comment]
> If this is merged, in the repo settings the required status check in the branch protection rules probably need to be updated. They are also outdated right now which is why the status for them doesn't get reported.

I've removed required checks in the meantime until this has been reviewed & merged.

**Comment by visr** [comment]
@DilumAluthge is this what you had in mind with this comment: https://github.com/julia-actions/julia-buildpkg/issues/14#issuecomment-1383525215?

**Comment by DilumAluthge** [comment]
I think we’ll need a couple additional tweaks. I’ll try to look into this in more detail next week.

**Comment by DilumAluthge** [comment]
I'm still looking into this. I need to get a bit more information on how eager/conservative registries work.

**Comment by SaschaMann** [comment]
superseded by #31

**Pull request closed without merging**
